baseURL = "https://kghobad.ir"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"
theme = "gokarna"
title = "Koosha Ghobadian"

[params]
  avatarAltText = "ghobadian"
  avatarSize = "size-m"
  avatarURL = "/images/profile.png"
  accentColor = "#FF4D4D"
  description = "Where innovation meets execution"
  footer = "Ghobadian"
  metaKeywords = ["blog", "ghobadian"]
  showBackToTopButton = true # true or false for "back to top" button on posts and pages
  togglePreviousAndNextButtons = true
  dateFormat = "2 January, 2006"


  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """



  socialIcons = [
    {name = "x", url = "https://x.com/kooooooooosha"},
    {name = "linkedin", url = "https://linkedin.com/in/ghobadian"},
    {name = "telegram", url = "https://t.me/koooooooosha"},
    {name = "email", url = "mailto:kooshaghobadian@gmail.com"},

  ]


[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/ghobadian"
    weight = 5


[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
  [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true

[minify]
    minifyOutput = true

